import { render, screen, fireEvent } from "@/lib/test-utils";
import { ArtifactModal } from "../ArtifactModal";
import type { StoryArtifact } from "@/lib/types/story";

// Mock Next.js Image component
jest.mock("next/image", () => ({
  __esModule: true,
  default: function MockImage({
    src,
    alt,
    onError,
  }: {
    src: string;
    alt: string;
    // eslint-disable-next-line no-unused-vars
    onError?: (e: React.SyntheticEvent<HTMLImageElement>) => void;
  }) {
    return <img src={src} alt={alt} data-testid="mock-image" onError={onError} />;
  },
}));

const mockImageArtifact: StoryArtifact = {
  id: "artifact-1",
  type: "image",
  url: "/placeholders/ai-response.jpg",
  title: "Screenshot of AI Response",
  caption: "The AI provided detailed guidance on the issue",
  alt: "AI chat showing legal advice response",
};

const mockDocumentArtifact: StoryArtifact = {
  id: "artifact-2",
  type: "document",
  url: "/placeholders/legal-letter.pdf",
  title: "Legal Letter Template",
  caption: "Template generated by Claude for formal complaint",
  alt: "Document showing formal letter structure",
  fileSize: "120 KB",
  pageCount: 2,
};

const mockScreenshotArtifact: StoryArtifact = {
  id: "artifact-3",
  type: "screenshot",
  url: "/placeholders/resolution-email.png",
  title: "Resolution Email",
  caption: "Confirmation email from the company",
  alt: "Email showing positive resolution",
};

describe("ArtifactModal Component", () => {
  const mockOnClose = jest.fn();

  beforeEach(() => {
    jest.clearAllMocks();
    // Reset body overflow style
    document.body.style.overflow = "unset";
  });

  afterEach(() => {
    // Clean up body overflow style
    document.body.style.overflow = "unset";
  });

  describe("Rendering Behavior", () => {
    it("returns null when isOpen is false", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={mockOnClose} />
      );
      expect(container.firstChild).toBeNull();
    });

    it("renders modal when isOpen is true", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByRole("dialog")).toBeInTheDocument();
    });
  });

  describe("Title and Header Display", () => {
    it("displays artifact title in header", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText("Screenshot of AI Response")).toBeInTheDocument();
    });

    it("has correct heading with aria-labelledby attribute", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const title = screen.getByText("Screenshot of AI Response");
      expect(title).toHaveAttribute("id", "artifact-modal-title");
    });
  });

  describe("Header Colors", () => {
    it("shows correct header color for image type (yellow)", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const header = container.querySelector(".flex.items-center.justify-between.p-4");
      expect(header).toHaveStyle({ backgroundColor: "#FFD700" });
    });

    it("shows correct header color for document type (coral)", () => {
      const { container } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const header = container.querySelector(".flex.items-center.justify-between.p-4");
      expect(header).toHaveStyle({ backgroundColor: "#FF6B6B" });
    });

    it("shows correct header color for screenshot type (mint)", () => {
      const { container } = render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const header = container.querySelector(".flex.items-center.justify-between.p-4");
      expect(header).toHaveStyle({ backgroundColor: "#00FF7F" });
    });
  });

  describe("Artifact Type Icons", () => {
    it("displays camera icon for image type", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const icon = screen.getByText("📷");
      expect(icon).toBeInTheDocument();
    });

    it("displays document icon for document type", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      const icons = screen.getAllByText("📄");
      // Document type shows icon in header and content area
      expect(icons.length).toBeGreaterThan(0);
    });

    it("displays laptop icon for screenshot type", () => {
      render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const icon = screen.getByText("💻");
      expect(icon).toBeInTheDocument();
    });
  });

  describe("Document-Specific Features", () => {
    it("displays page count and file size for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      // Both header and content area show page count and file size
      const pageInfo = screen.getAllByText(/2 pages/);
      expect(pageInfo.length).toBeGreaterThan(0);
      const sizeInfo = screen.getAllByText(/120 KB/);
      expect(sizeInfo.length).toBeGreaterThan(0);
    });

    it("shows demo mode message for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText(/PDF preview not available in demo mode/i)).toBeInTheDocument();
    });

    it('shows "Open in New Tab" button only for documents', () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.getByText("Open in New Tab ↗")).toBeInTheDocument();

      // Rerender with image artifact
      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.queryByText("Open in New Tab ↗")).not.toBeInTheDocument();

      // Rerender with screenshot artifact
      rerender(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.queryByText("Open in New Tab ↗")).not.toBeInTheDocument();
    });

    it('"Open in New Tab" link has correct attributes', () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      const link = screen.getByText("Open in New Tab ↗").closest("a");
      expect(link).toHaveAttribute("href", mockDocumentArtifact.url);
      expect(link).toHaveAttribute("target", "_blank");
      expect(link).toHaveAttribute("rel", "noopener noreferrer");
    });
  });

  describe("Image Display", () => {
    it("displays image for image type artifacts", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const image = screen.getByTestId("mock-image");
      expect(image).toBeInTheDocument();
      expect(image).toHaveAttribute("alt", mockImageArtifact.alt);
    });

    it("displays image for screenshot type artifacts", () => {
      render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const image = screen.getByTestId("mock-image");
      expect(image).toBeInTheDocument();
      expect(image).toHaveAttribute("alt", mockScreenshotArtifact.alt);
    });

    it("does not display image for document type artifacts", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.queryByTestId("mock-image")).not.toBeInTheDocument();
    });
  });

  describe("Caption Display", () => {
    it("displays caption in footer for image artifacts", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      // Caption appears in footer and possibly header
      const captions = screen.getAllByText(mockImageArtifact.caption);
      expect(captions.length).toBeGreaterThan(0);
    });

    it("displays caption in footer for document artifacts", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText(mockDocumentArtifact.caption)).toBeInTheDocument();
    });
  });

  describe("Download Functionality", () => {
    it("has Download button", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText("Download")).toBeInTheDocument();
    });

    it("Download link has correct href", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const downloadLink = screen.getByText("Download").closest("a");
      expect(downloadLink).toHaveAttribute("href", mockImageArtifact.url);
      expect(downloadLink).toHaveAttribute("download");
    });
  });

  describe("Close Functionality", () => {
    it("calls onClose when X button clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const closeButton = screen.getByRole("button", { name: /close modal/i });
      fireEvent.click(closeButton);
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("calls onClose when backdrop clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const backdrop = screen.getByRole("dialog");
      fireEvent.click(backdrop);
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("does not close when modal content clicked", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".relative.max-w-4xl");
      fireEvent.click(modalContent!);
      expect(mockOnClose).not.toHaveBeenCalled();
    });

    it("calls onClose when ESC key pressed", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      fireEvent.keyDown(document, { key: "Escape" });
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("does not call onClose for other keys", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      fireEvent.keyDown(document, { key: "Enter" });
      fireEvent.keyDown(document, { key: "Space" });
      expect(mockOnClose).not.toHaveBeenCalled();
    });
  });

  describe("Accessibility", () => {
    it("has correct aria attributes for dialog", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const dialog = screen.getByRole("dialog");
      expect(dialog).toHaveAttribute("aria-modal", "true");
      expect(dialog).toHaveAttribute("aria-labelledby", "artifact-modal-title");
    });

    it("has accessible close button with aria-label", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const closeButton = screen.getByRole("button", { name: /close modal/i });
      expect(closeButton).toHaveAttribute("aria-label", "Close modal");
    });

    it("image has correct alt text", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const image = screen.getByAltText(mockImageArtifact.alt);
      expect(image).toBeInTheDocument();
    });
  });

  describe("Body Scroll Lock", () => {
    it("locks body scroll when modal opens", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(document.body.style.overflow).toBe("hidden");
    });

    it("unlocks body scroll when modal closes", () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={mockOnClose} />);
      expect(document.body.style.overflow).toBe("unset");
    });

    it("unlocks body scroll when component unmounts", () => {
      const { unmount } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      unmount();
      expect(document.body.style.overflow).toBe("unset");
    });
  });

  describe("Event Listener Cleanup", () => {
    it("removes keydown listener when modal closes", () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );

      // Close modal
      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={mockOnClose} />);

      // Try pressing escape
      fireEvent.keyDown(document, { key: "Escape" });

      // onClose should not be called because listener was removed
      expect(mockOnClose).not.toHaveBeenCalled();
    });

    it("removes keydown listener when component unmounts", () => {
      const { unmount } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );

      unmount();

      // Try pressing escape after unmount
      fireEvent.keyDown(document, { key: "Escape" });

      // onClose should not be called because listener was removed
      expect(mockOnClose).not.toHaveBeenCalled();
    });
  });

  describe("Memphis Design System", () => {
    it("has Memphis design shadow on modal", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".relative.max-w-4xl");
      expect(modalContent).toHaveStyle({ boxShadow: "12px 12px 0px #000000" });
    });

    it("has Memphis design shadow on close button", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const closeButton = screen.getByRole("button", { name: /close modal/i });
      expect(closeButton).toHaveStyle({ boxShadow: "3px 3px 0px #000000" });
    });

    it("has Memphis design shadow on Download button", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const downloadButton = screen.getByText("Download");
      expect(downloadButton).toHaveStyle({ boxShadow: "3px 3px 0px #000000" });
    });

    it('has Memphis design shadow on "Open in New Tab" button for documents', () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      const openButton = screen.getByText("Open in New Tab ↗");
      expect(openButton).toHaveStyle({ boxShadow: "3px 3px 0px #FFD700" });
    });

    it("applies bold borders typical of Memphis design", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".border-4.border-black");
      expect(modalContent).toBeInTheDocument();
    });
  });

  describe("Document Metadata", () => {
    it("does not display page count when not provided", () => {
      const docWithoutMetadata: StoryArtifact = {
        ...mockDocumentArtifact,
        pageCount: undefined,
        fileSize: undefined,
      };
      render(<ArtifactModal artifact={docWithoutMetadata} isOpen={true} onClose={mockOnClose} />);
      expect(screen.queryByText(/pages/)).not.toBeInTheDocument();
    });

    it("displays file size with correct formatting", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      const fileSize = screen.getAllByText(/120 KB/);
      expect(fileSize.length).toBeGreaterThan(0);
    });
  });

  describe("Modal Layout", () => {
    it("has correct z-index for modal overlay", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const backdrop = screen.getByRole("dialog");
      expect(backdrop).toHaveClass("z-50");
    });

    it("has semi-transparent dark background", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const backdrop = screen.getByRole("dialog");
      expect(backdrop).toHaveStyle({ backgroundColor: "rgba(0, 0, 0, 0.85)" });
    });

    it("limits modal height to 90vh", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".max-h-\\[90vh\\]");
      expect(modalContent).toBeInTheDocument();
    });
  });
});
