import { render, screen, fireEvent } from "@/lib/test-utils";
import { ArtifactModal } from "../ArtifactModal";
import type { StoryArtifact } from "@/lib/types/story";

const mockImageArtifact: StoryArtifact = {
  id: "artifact-1",
  type: "image",
  url: "/placeholders/ai-response.jpg",
  title: "Screenshot of AI Response",
  caption: "The AI provided detailed guidance on the issue",
  alt: "AI chat showing legal advice response",
};

const mockDocumentArtifact: StoryArtifact = {
  id: "artifact-2",
  type: "document",
  url: "/placeholders/legal-letter.pdf",
  title: "Legal Letter Template",
  caption: "Template generated by Claude for formal complaint",
  alt: "Document showing formal letter structure",
  fileSize: "120 KB",
  pageCount: 2,
};

const mockScreenshotArtifact: StoryArtifact = {
  id: "artifact-3",
  type: "screenshot",
  url: "/placeholders/screenshot.png",
  title: "Resolution Email Screenshot",
  caption: "Confirmation email from the company",
  alt: "Email showing positive resolution",
};

describe("Organic ArtifactModal Component", () => {
  let onCloseMock: jest.Mock;

  beforeEach(() => {
    onCloseMock = jest.fn();
    // Reset body overflow style before each test
    document.body.style.overflow = "unset";
  });

  afterEach(() => {
    // Clean up after each test
    document.body.style.overflow = "unset";
  });

  describe("Modal Visibility", () => {
    it("returns null when isOpen is false", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={onCloseMock} />
      );
      expect(container.firstChild).toBeNull();
    });

    it("renders modal when isOpen is true", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(screen.getByRole("dialog")).toBeInTheDocument();
    });
  });

  describe("Content Display", () => {
    it("displays artifact title in header", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(screen.getByText("Screenshot of AI Response")).toBeInTheDocument();
    });

    it("displays artifact caption in footer", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(
        screen.getByText("The AI provided detailed guidance on the issue")
      ).toBeInTheDocument();
    });

    it("displays page count and file size for documents in header", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      // The text appears both in header and content area, so check for multiple occurrences
      const pageCountElements = screen.getAllByText(/2 pages/);
      expect(pageCountElements.length).toBeGreaterThanOrEqual(1);

      const fileSizeElements = screen.getAllByText(/120 KB/);
      expect(fileSizeElements.length).toBeGreaterThanOrEqual(1);
    });

    it("displays page count and file size for documents in content area", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      // The document content area also shows page count and file size
      const pageCountElements = screen.getAllByText(/2 pages/);
      expect(pageCountElements.length).toBeGreaterThan(0);
    });

    it("displays demo mode message for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(screen.getByText(/PDF preview not available in demo mode/i)).toBeInTheDocument();
    });
  });

  describe("Button Visibility", () => {
    it('shows "Open in New Tab" button only for documents', () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      expect(screen.queryByText("Open in New Tab")).not.toBeInTheDocument();

      rerender(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />
      );
      expect(screen.getByText("Open in New Tab")).toBeInTheDocument();

      rerender(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={onCloseMock} />
      );
      expect(screen.queryByText("Open in New Tab")).not.toBeInTheDocument();
    });

    it("always shows Download button", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(screen.getByText("Download")).toBeInTheDocument();
    });
  });

  describe("User Interactions", () => {
    it("calls onClose when X button clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const closeButton = screen.getByLabelText("Close modal");
      fireEvent.click(closeButton);
      expect(onCloseMock).toHaveBeenCalledTimes(1);
    });

    it("calls onClose when backdrop clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const backdrop = screen.getByRole("dialog");
      fireEvent.click(backdrop);
      expect(onCloseMock).toHaveBeenCalledTimes(1);
    });

    it("does not call onClose when modal content clicked", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const modalContent = container.querySelector(".rounded-2xl");
      expect(modalContent).toBeInTheDocument();
      fireEvent.click(modalContent!);
      expect(onCloseMock).not.toHaveBeenCalled();
    });

    it("calls onClose when ESC key pressed", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      fireEvent.keyDown(document, { key: "Escape" });
      expect(onCloseMock).toHaveBeenCalledTimes(1);
    });

    it("does not call onClose when other keys pressed", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      fireEvent.keyDown(document, { key: "Enter" });
      fireEvent.keyDown(document, { key: "a" });
      expect(onCloseMock).not.toHaveBeenCalled();
    });
  });

  describe("Accessibility", () => {
    it("has correct aria attributes for accessibility", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const dialog = screen.getByRole("dialog");
      expect(dialog).toHaveAttribute("aria-modal", "true");
      expect(dialog).toHaveAttribute("aria-labelledby", "artifact-modal-title");
    });

    it("has accessible close button with aria-label", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const closeButton = screen.getByLabelText("Close modal");
      expect(closeButton).toBeInTheDocument();
    });

    it("sets the modal title with correct id for aria-labelledby", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const title = document.getElementById("artifact-modal-title");
      expect(title).toBeInTheDocument();
      expect(title?.textContent).toBe("Screenshot of AI Response");
    });
  });

  describe("Download and External Links", () => {
    it("download link has correct href for images", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const downloadLink = screen.getByText("Download");
      expect(downloadLink).toHaveAttribute("href", "/placeholders/ai-response.jpg");
      expect(downloadLink).toHaveAttribute("download");
    });

    it("download link has correct href for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      const downloadLink = screen.getByText("Download");
      expect(downloadLink).toHaveAttribute("href", "/placeholders/legal-letter.pdf");
      expect(downloadLink).toHaveAttribute("download");
    });

    it("open in new tab link has correct attributes for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      const openLink = screen.getByText("Open in New Tab");
      expect(openLink).toHaveAttribute("href", "/placeholders/legal-letter.pdf");
      expect(openLink).toHaveAttribute("target", "_blank");
      expect(openLink).toHaveAttribute("rel", "noopener noreferrer");
    });
  });

  describe("Organic Theme Styling", () => {
    it("applies rounded corners to modal", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const modalContent = container.querySelector(".rounded-2xl");
      expect(modalContent).toBeInTheDocument();
    });

    it("applies soft shadow styling", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const modalContent = container.querySelector(".shadow-2xl");
      expect(modalContent).toBeInTheDocument();
    });

    it("applies sage green gradient for image type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const header = container.querySelector(".from-\\[\\#81b29a\\]");
      expect(header).toBeInTheDocument();
      expect(header).toHaveClass("to-[#6a9a82]");
    });

    it("applies warm yellow gradient for screenshot type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const header = container.querySelector(".from-\\[\\#f2cc8f\\]");
      expect(header).toBeInTheDocument();
      expect(header).toHaveClass("to-[#e5b97a]");
    });

    it("applies terracotta gradient for document type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const header = container.querySelector(".from-\\[\\#e07a5f\\]");
      expect(header).toBeInTheDocument();
      expect(header).toHaveClass("to-[#c96a52]");
    });

    it("has earthy background color in content area", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const contentArea = container.querySelector(".bg-\\[\\#fdf8f3\\]");
      expect(contentArea).toBeInTheDocument();
    });

    it("applies rounded corners to buttons", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      const downloadButton = screen.getByText("Download");
      expect(downloadButton).toHaveClass("rounded-full");

      const openButton = screen.getByText("Open in New Tab");
      expect(openButton).toHaveClass("rounded-full");
    });

    it("has rounded close button", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const closeButton = screen.getByLabelText("Close modal");
      expect(closeButton).toHaveClass("rounded-full");
    });
  });

  describe("Body Scroll Lock", () => {
    it("locks body scroll when modal opens", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(document.body.style.overflow).toBe("hidden");
    });

    it("unlocks body scroll when modal closes", () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={onCloseMock} />);
      expect(document.body.style.overflow).toBe("unset");
    });

    it("unlocks body scroll when component unmounts", () => {
      const { unmount } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      unmount();
      expect(document.body.style.overflow).toBe("unset");
    });
  });

  describe("Event Listener Cleanup", () => {
    it("removes keydown event listener when modal closes", () => {
      const addEventListenerSpy = jest.spyOn(document, "addEventListener");
      const removeEventListenerSpy = jest.spyOn(document, "removeEventListener");

      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );

      expect(addEventListenerSpy).toHaveBeenCalledWith("keydown", expect.any(Function));

      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={onCloseMock} />);

      expect(removeEventListenerSpy).toHaveBeenCalledWith("keydown", expect.any(Function));

      addEventListenerSpy.mockRestore();
      removeEventListenerSpy.mockRestore();
    });

    it("removes keydown event listener when component unmounts", () => {
      const removeEventListenerSpy = jest.spyOn(document, "removeEventListener");

      const { unmount } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );

      unmount();

      expect(removeEventListenerSpy).toHaveBeenCalledWith("keydown", expect.any(Function));

      removeEventListenerSpy.mockRestore();
    });
  });

  describe("Artifact Type Icons", () => {
    it("renders camera icon for image type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />
      );
      // Camera emoji unicode 128247
      const icon = container.querySelector("span.text-xl");
      expect(icon).toBeInTheDocument();
      expect(icon?.textContent).toMatch(/📷/);
    });

    it("renders document icon for document type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />
      );
      // Document emoji unicode 128196
      const icon = container.querySelector("span.text-xl");
      expect(icon).toBeInTheDocument();
      expect(icon?.textContent).toMatch(/📄/);
    });

    it("renders laptop icon for screenshot type", () => {
      const { container } = render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={onCloseMock} />
      );
      // Laptop emoji unicode 128187
      const icon = container.querySelector("span.text-xl");
      expect(icon).toBeInTheDocument();
      expect(icon?.textContent).toMatch(/💻/);
    });
  });

  describe("Image Rendering", () => {
    it("renders Image component for image type", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      const image = screen.getByAltText("AI chat showing legal advice response");
      expect(image).toBeInTheDocument();
    });

    it("renders Image component for screenshot type", () => {
      render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={onCloseMock} />
      );
      const image = screen.getByAltText("Email showing positive resolution");
      expect(image).toBeInTheDocument();
    });

    it("does not render Image component for document type", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      const image = screen.queryByAltText("Document showing formal letter structure");
      expect(image).not.toBeInTheDocument();
    });
  });

  describe("Document Placeholder", () => {
    it("renders document placeholder for document type", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={onCloseMock} />);
      // The title appears both in header and content area
      const titleElements = screen.getAllByText("Legal Letter Template");
      expect(titleElements.length).toBeGreaterThanOrEqual(1);

      expect(screen.getByText(/PDF preview not available/i)).toBeInTheDocument();
    });

    it("does not render document placeholder for image type", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={onCloseMock} />);
      expect(screen.queryByText(/PDF preview not available/i)).not.toBeInTheDocument();
    });
  });
});
