import { render, screen } from "@/lib/test-utils";
import { StoryArtifacts } from "../memphis/StoryArtifacts";
import type { StoryArtifact } from "@/lib/types/story";

const mockArtifacts: StoryArtifact[] = [
  {
    id: "artifact-1",
    type: "image",
    title: "Screenshot of AI Response",
    caption: "The AI provided detailed guidance on the issue",
    alt: "AI chat showing legal advice response",
  },
  {
    id: "artifact-2",
    type: "document",
    title: "Legal Letter Template",
    caption: "Template generated by Claude for formal complaint",
    alt: "Document showing formal letter structure",
  },
  {
    id: "artifact-3",
    type: "screenshot",
    title: "Resolution Email",
    caption: "Confirmation email from the company",
    alt: "Email showing positive resolution",
  },
];

const singleArtifact: StoryArtifact[] = [
  {
    id: "artifact-single",
    type: "image",
    title: "Single Evidence Item",
    caption: "A single piece of evidence",
    alt: "Single artifact alt text",
  },
];

describe("StoryArtifacts Component", () => {
  it("renders without errors when artifacts are provided", () => {
    expect(() => render(<StoryArtifacts artifacts={mockArtifacts} />)).not.toThrow();
  });

  it("returns null when artifacts array is empty", () => {
    const { container } = render(<StoryArtifacts artifacts={[]} />);
    expect(container.firstChild).toBeNull();
  });

  it("returns null when artifacts is undefined", () => {
    // @ts-expect-error Testing undefined case
    const { container } = render(<StoryArtifacts artifacts={undefined} />);
    expect(container.firstChild).toBeNull();
  });

  it('displays "Evidence & Documents" section heading', () => {
    render(<StoryArtifacts artifacts={mockArtifacts} />);
    expect(screen.getByText("Evidence & Documents")).toBeInTheDocument();
  });

  it("renders the correct number of artifacts", () => {
    render(<StoryArtifacts artifacts={mockArtifacts} />);

    // Check that all artifact titles are present
    expect(screen.getByText("Screenshot of AI Response")).toBeInTheDocument();
    expect(screen.getByText("Legal Letter Template")).toBeInTheDocument();
    expect(screen.getByText("Resolution Email")).toBeInTheDocument();
  });

  it("displays artifact titles", () => {
    render(<StoryArtifacts artifacts={singleArtifact} />);
    expect(screen.getByText("Single Evidence Item")).toBeInTheDocument();
  });

  it("displays artifact captions", () => {
    render(<StoryArtifacts artifacts={mockArtifacts} />);

    expect(screen.getByText("The AI provided detailed guidance on the issue")).toBeInTheDocument();
    expect(
      screen.getByText("Template generated by Claude for formal complaint")
    ).toBeInTheDocument();
    expect(screen.getByText("Confirmation email from the company")).toBeInTheDocument();
  });

  it("displays artifact alt text", () => {
    render(<StoryArtifacts artifacts={mockArtifacts} />);

    expect(screen.getByText("AI chat showing legal advice response")).toBeInTheDocument();
    expect(screen.getByText("Document showing formal letter structure")).toBeInTheDocument();
    expect(screen.getByText("Email showing positive resolution")).toBeInTheDocument();
  });

  it("renders image type artifacts with correct icon", () => {
    const imageArtifacts: StoryArtifact[] = [
      {
        id: "image-1",
        type: "image",
        title: "Image Artifact",
        caption: "Image caption",
        alt: "Image alt text",
      },
    ];

    const { container } = render(<StoryArtifacts artifacts={imageArtifacts} />);

    // Check that the image icon (📷 - camera emoji) is rendered
    const icon = container.querySelector("span.text-lg");
    expect(icon).toBeInTheDocument();
    expect(icon?.textContent).toBe("📷");
  });

  it("renders document type artifacts with correct icon", () => {
    const documentArtifacts: StoryArtifact[] = [
      {
        id: "doc-1",
        type: "document",
        title: "Document Artifact",
        caption: "Document caption",
        alt: "Document alt text",
      },
    ];

    const { container } = render(<StoryArtifacts artifacts={documentArtifacts} />);

    // Check that the document icon (📄 - page facing up emoji) is rendered
    const icon = container.querySelector("span.text-lg");
    expect(icon).toBeInTheDocument();
    expect(icon?.textContent).toBe("📄");
  });

  it("renders screenshot type artifacts with correct icon", () => {
    const screenshotArtifacts: StoryArtifact[] = [
      {
        id: "screenshot-1",
        type: "screenshot",
        title: "Screenshot Artifact",
        caption: "Screenshot caption",
        alt: "Screenshot alt text",
      },
    ];

    const { container } = render(<StoryArtifacts artifacts={screenshotArtifacts} />);

    // Check that the screenshot icon (💻 - laptop emoji) is rendered
    const icon = container.querySelector("span.text-lg");
    expect(icon).toBeInTheDocument();
    expect(icon?.textContent).toBe("💻");
  });

  it("renders multiple artifacts with different types correctly", () => {
    render(<StoryArtifacts artifacts={mockArtifacts} />);

    // Verify all three different artifact types are rendered
    expect(screen.getByText("Screenshot of AI Response")).toBeInTheDocument();
    expect(screen.getByText("Legal Letter Template")).toBeInTheDocument();
    expect(screen.getByText("Resolution Email")).toBeInTheDocument();
  });

  it("renders single artifact correctly", () => {
    render(<StoryArtifacts artifacts={singleArtifact} />);

    expect(screen.getByText("Evidence & Documents")).toBeInTheDocument();
    expect(screen.getByText("Single Evidence Item")).toBeInTheDocument();
    expect(screen.getByText("A single piece of evidence")).toBeInTheDocument();
    expect(screen.getByText("Single artifact alt text")).toBeInTheDocument();
  });

  it("applies correct styling classes to the container", () => {
    const { container } = render(<StoryArtifacts artifacts={mockArtifacts} />);

    const artifactContainer = container.querySelector(".mt-10");
    expect(artifactContainer).toBeInTheDocument();
  });

  it("applies Memphis design styling to artifact cards", () => {
    const { container } = render(<StoryArtifacts artifacts={singleArtifact} />);

    // Check for Memphis-specific classes
    const artifactCard = container.querySelector(
      ".bg-gray-100.border-3.border-black.shadow-memphis-sm"
    );
    expect(artifactCard).toBeInTheDocument();
  });
});
