import { render, screen, fireEvent } from "@/lib/test-utils";
import { ArtifactModal } from "../ArtifactModal";
import type { StoryArtifact } from "@/lib/types/story";

// Mock Next.js Image component
jest.mock("next/image", () => ({
  __esModule: true,
  default: function MockImage({
    src,
    alt,
    onError,
  }: {
    src: string;
    alt: string;
    onError?: React.ReactEventHandler<HTMLImageElement>;
  }) {
    return <img src={src} alt={alt} onError={onError} data-testid="artifact-image" />;
  },
}));

const mockImageArtifact: StoryArtifact = {
  id: "img-1",
  type: "image",
  url: "/placeholders/screenshot.jpg",
  title: "AI Response Screenshot",
  caption: "The AI provided detailed guidance",
  alt: "Screenshot showing AI chat response",
};

const mockDocumentArtifact: StoryArtifact = {
  id: "doc-1",
  type: "document",
  url: "/placeholders/legal-letter.pdf",
  title: "Legal Letter Template",
  caption: "Template generated by Claude",
  alt: "Document showing formal letter structure",
  fileSize: "120 KB",
  pageCount: 2,
};

const mockScreenshotArtifact: StoryArtifact = {
  id: "screenshot-1",
  type: "screenshot",
  url: "/placeholders/resolution-email.png",
  title: "Resolution Email",
  caption: "Confirmation email from company",
  alt: "Email showing positive resolution",
};

describe("ArtifactModal Component", () => {
  const mockOnClose = jest.fn();

  beforeEach(() => {
    mockOnClose.mockClear();
  });

  describe("Visibility and Basic Rendering", () => {
    it("returns null when isOpen is false", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={mockOnClose} />
      );
      expect(container.firstChild).toBeNull();
    });

    it("renders modal when isOpen is true", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByRole("dialog")).toBeInTheDocument();
    });

    it("displays artifact title in header", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText("AI Response Screenshot")).toBeInTheDocument();
    });

    it("displays artifact caption in footer", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText("The AI provided detailed guidance")).toBeInTheDocument();
    });
  });

  describe("Document-Specific Features", () => {
    it("displays page count and file size for documents", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);

      // Check that metadata appears in both header and content area
      const pageCountElements = screen.getAllByText(/2 pages/);
      expect(pageCountElements.length).toBe(2); // Header and content area

      const fileSizeElements = screen.getAllByText(/120 KB/);
      expect(fileSizeElements.length).toBe(2); // Header and content area
    });

    it("shows document placeholder with demo message", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.getByText(/PDF preview not available in demo mode/i)).toBeInTheDocument();
    });

    it('shows "Open in New Tab" button only for documents', () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.getByText("Open in New Tab")).toBeInTheDocument();

      // Rerender with image artifact
      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(screen.queryByText("Open in New Tab")).not.toBeInTheDocument();
    });

    it('"Open in New Tab" button has correct attributes', () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);
      const openButton = screen.getByText("Open in New Tab").closest("a");
      expect(openButton).toHaveAttribute("href", mockDocumentArtifact.url);
      expect(openButton).toHaveAttribute("target", "_blank");
      expect(openButton).toHaveAttribute("rel", "noopener noreferrer");
    });
  });

  describe("Image Display", () => {
    it("renders image for image type artifacts", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const image = screen.getByTestId("artifact-image");
      expect(image).toBeInTheDocument();
      expect(image).toHaveAttribute("src", mockImageArtifact.url);
      expect(image).toHaveAttribute("alt", mockImageArtifact.alt);
    });

    it("renders image for screenshot type artifacts", () => {
      render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const image = screen.getByTestId("artifact-image");
      expect(image).toBeInTheDocument();
      expect(image).toHaveAttribute("src", mockScreenshotArtifact.url);
      expect(image).toHaveAttribute("alt", mockScreenshotArtifact.alt);
    });

    it("handles image load error", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const image = screen.getByTestId("artifact-image");

      // Trigger error
      fireEvent.error(image);

      // Error handler should hide the image and show fallback
      expect(image).toHaveStyle({ display: "none" });
    });
  });

  describe("Close Functionality", () => {
    it("calls onClose when X button clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const closeButton = screen.getByLabelText("Close modal");
      fireEvent.click(closeButton);
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("calls onClose when backdrop clicked", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const backdrop = screen.getByRole("dialog");
      fireEvent.click(backdrop);
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("does not call onClose when modal content is clicked", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );

      // Click on the modal content (not the backdrop)
      const modalContent = container.querySelector(".max-w-4xl");
      if (modalContent) {
        fireEvent.click(modalContent);
        expect(mockOnClose).not.toHaveBeenCalled();
      }
    });

    it("calls onClose when ESC key pressed", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      fireEvent.keyDown(document, { key: "Escape" });
      expect(mockOnClose).toHaveBeenCalledTimes(1);
    });

    it("does not call onClose when other keys are pressed", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      fireEvent.keyDown(document, { key: "Enter" });
      fireEvent.keyDown(document, { key: "Tab" });
      expect(mockOnClose).not.toHaveBeenCalled();
    });
  });

  describe("Body Scroll Lock", () => {
    it("locks body scroll when modal is open", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      expect(document.body.style.overflow).toBe("hidden");
    });

    it("restores body scroll when modal is closed", () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      rerender(<ArtifactModal artifact={mockImageArtifact} isOpen={false} onClose={mockOnClose} />);
      expect(document.body.style.overflow).toBe("unset");
    });

    it("restores body scroll when component unmounts", () => {
      const { unmount } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(document.body.style.overflow).toBe("hidden");

      unmount();
      expect(document.body.style.overflow).toBe("unset");
    });
  });

  describe("Accessibility", () => {
    it("has correct aria attributes for dialog", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const dialog = screen.getByRole("dialog");
      expect(dialog).toHaveAttribute("aria-modal", "true");
      expect(dialog).toHaveAttribute("aria-labelledby", "artifact-modal-title");
    });

    it("has correct id on title element", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const title = screen.getByText(mockImageArtifact.title);
      expect(title).toHaveAttribute("id", "artifact-modal-title");
    });

    it("close button has aria-label", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const closeButton = screen.getByLabelText("Close modal");
      expect(closeButton).toBeInTheDocument();
    });
  });

  describe("Download Functionality", () => {
    it("download link has correct href", () => {
      render(<ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />);
      const downloadLink = screen.getByText("Download").closest("a");
      expect(downloadLink).toHaveAttribute("href", mockImageArtifact.url);
      expect(downloadLink).toHaveAttribute("download");
    });

    it("download button is present for all artifact types", () => {
      const { rerender } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.getByText("Download")).toBeInTheDocument();

      rerender(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.getByText("Download")).toBeInTheDocument();

      rerender(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      expect(screen.getByText("Download")).toBeInTheDocument();
    });
  });

  describe("Japanese Theme Styling", () => {
    it("applies Japanese theme background color to modal content", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".bg-\\[\\#faf8f5\\]");
      expect(modalContent).toBeInTheDocument();
    });

    it("applies Japanese theme border color", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".border-\\[\\#d4d0c8\\]");
      expect(modalContent).toBeInTheDocument();
    });

    it("applies Japanese theme text color", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const title = container.querySelector(".text-\\[\\#1a1a1a\\]");
      expect(title).toBeInTheDocument();
    });

    it("applies Japanese theme content background", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const contentArea = container.querySelector(".bg-\\[\\#f5f2ed\\]");
      expect(contentArea).toBeInTheDocument();
    });

    it("has accent line with gradient", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const accentLine = container.querySelector(
        ".bg-gradient-to-r.from-transparent.via-\\[\\#c4a77d\\]"
      );
      expect(accentLine).toBeInTheDocument();
    });

    it("applies muted colors to metadata text", () => {
      const { container } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const metadataText = container.querySelector(".text-\\[\\#6b6b6b\\]");
      expect(metadataText).toBeInTheDocument();
    });

    it("applies minimal styling to buttons", () => {
      render(<ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />);

      const downloadButton = screen.getByText("Download").closest("a");
      expect(downloadButton?.className).toContain("border-[#d4d0c8]");
      expect(downloadButton?.className).toContain("text-[#1a1a1a]");

      const openButton = screen.getByText("Open in New Tab").closest("a");
      expect(openButton?.className).toContain("bg-[#1a1a1a]");
      expect(openButton?.className).toContain("text-white");
    });
  });

  describe("Artifact Type Icons", () => {
    it("displays camera icon for image artifacts", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const icon = container.querySelector(".text-\\[\\#8b7355\\] span");
      expect(icon).toBeInTheDocument();
      // Camera emoji: &#128247; = 📷
      expect(icon?.textContent).toBe("📷");
    });

    it("displays document icon for document artifacts", () => {
      const { container } = render(
        <ArtifactModal artifact={mockDocumentArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const icon = container.querySelector(".text-\\[\\#8b7355\\] span");
      expect(icon).toBeInTheDocument();
      // Document emoji: &#128196; = 📄
      expect(icon?.textContent).toBe("📄");
    });

    it("displays laptop icon for screenshot artifacts", () => {
      const { container } = render(
        <ArtifactModal artifact={mockScreenshotArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const icon = container.querySelector(".text-\\[\\#8b7355\\] span");
      expect(icon).toBeInTheDocument();
      // Laptop emoji: &#128187; = 💻
      expect(icon?.textContent).toBe("💻");
    });
  });

  describe("Layout and Structure", () => {
    it("renders header, content, and footer sections", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );

      // Header with border-b
      const header = container.querySelector(".border-b");
      expect(header).toBeInTheDocument();

      // Content area with overflow-auto
      const content = container.querySelector(".overflow-auto");
      expect(content).toBeInTheDocument();

      // Footer with border-t
      const footer = container.querySelector(".border-t");
      expect(footer).toBeInTheDocument();
    });

    it("modal content has max width constraint", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".max-w-4xl");
      expect(modalContent).toBeInTheDocument();
    });

    it("modal content has max height constraint", () => {
      const { container } = render(
        <ArtifactModal artifact={mockImageArtifact} isOpen={true} onClose={mockOnClose} />
      );
      const modalContent = container.querySelector(".max-h-\\[90vh\\]");
      expect(modalContent).toBeInTheDocument();
    });
  });
});
